#!/usr/bin/env python3
"""Generate src/font.ts: a 1-bit bitmap of every glyph the dashboard can draw.

The PNG capture has no font engine and no runtime dependencies, so the glyphs
are baked in at build time from a real monospace face. Run this once when the
glyph set changes; the output is committed. Needs Pillow, which is a tool for
this script only and not something TeamAI itself depends on.
"""
import base64
import sys
from pathlib import Path

from PIL import Image, ImageDraw, ImageFont

CELL_W, CELL_H = 9, 18
FONT = "/System/Library/Fonts/Menlo.ttc"
SIZE = 15
THRESHOLD = 110

# Printable ASCII plus the handful of symbols src/tui.ts and src/redact.ts use.
ASCII = "".join(chr(c) for c in range(32, 127))
EXTRA = "─━│┌┐└┘●↑↓…→—•"
GLYPHS = ASCII + EXTRA

font = ImageFont.truetype(FONT, SIZE)
# Baseline: place glyphs so that ascenders and descenders both fit the cell.
ascent, descent = font.getmetrics()
baseline = (CELL_H - (ascent + descent)) // 2 + ascent

rows = bytearray()
for glyph in GLYPHS:
    img = Image.new("L", (CELL_W, CELL_H), 0)
    d = ImageDraw.Draw(img)
    d.text((0, baseline), glyph, font=font, fill=255, anchor="ls")
    px = img.load()
    for y in range(CELL_H):
        bits = 0
        for x in range(CELL_W):
            if px[x, y] >= THRESHOLD:
                bits |= 1 << (15 - x)
        rows += bits.to_bytes(2, "big")

out = Path(__file__).resolve().parent.parent / "src" / "font.ts"
out.write_text(
    "// Generated by scripts/gen-font.py — do not edit by hand.\n"
    "// One 1-bit bitmap per glyph: CELL_HEIGHT rows of big-endian uint16, bit 15\n"
    "// being the leftmost of CELL_WIDTH columns. Glyph order matches GLYPHS.\n"
    f"export const CELL_WIDTH = {CELL_W};\n"
    f"export const CELL_HEIGHT = {CELL_H};\n"
    f"export const GLYPHS = {GLYPHS!r};\n"
    f"export const BITMAP = '{base64.b64encode(bytes(rows)).decode()}';\n",
    encoding="utf-8",
)
print(f"wrote {out} ({len(GLYPHS)} glyphs, {len(rows)} bytes)", file=sys.stderr)
